kind: PersistentVolume
apiVersion: v1
metadata:
  name: blogs-uploads-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 0.1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/blogs_uploads"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blogs-depl
spec:
  serviceName: "local-service"
  replicas: 1
  selector:
    matchLabels:
      app: blogs
  template:
    metadata:
      labels:
        app: blogs
    spec:
      containers:
        - name: blogs
          image: akshaypatil0/blogs
          imagePullPolicy: Never
          env:
            - name: NATS_CLUSTER_ID
              value: fibimarket

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_URL
              value: "http://nats-srv:4222"

            - name: MONGO_URI
              value: "mongodb://blogs-mongo-srv:27017/blogs"

            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

            - name: AWS_ID
              valueFrom:
                secretKeyRef:
                  name: aws-id
                  key: AWS_ID

            - name: AWS_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET
          volumeMounts:
            - name: local-vol
              mountPath: /uploads
  volumeClaimTemplates:
    - metadata:
        name: local-vol
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-storage"
        resources:
          requests:
            storage: 0.1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: blogs-srv
spec:
  selector:
    app: blogs
  ports:
    - name: blogs
      protocol: TCP
      port: 4000
      targetPort: 4000
