apiVersion: v1
kind: Namespace
metadata:
  name: fibi

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  namespace: fibi
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          # - path: /api/users/*
          #   backend:
          #     serviceName: "users-srv"
          #     servicePort: 4000

          # - path: /api/products/*
          #   backend:
          #     serviceName: "products-srv"
          #     servicePort: 4000

          # - path: /api/orders/*
          #   backend:
          #     serviceName: "orders-srv"
          #     servicePort: 4000

          # - path: /api/blogs/*
          #   backend:
          #     serviceName: "blogs-srv"
          #     servicePort: 4000

          - path: /*
            backend:
              serviceName: "ui-srv"
              servicePort: 80
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-service
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/use-regex: "true"
# spec:
#   rules:
#     - host: fibimarket.dev
#       http:
#         paths:
#           - backend:
#               service:
#                 name: users-srv
#                 port:
#                   number: 4000
#             path: /api/users/?(.*)
#             pathType: Exact

#           - backend:
#               service:
#                 name: products-srv
#                 port:
#                   number: 4000
#             path: /api/products/?(.*)
#             pathType: Exact

#           - backend:
#               service:
#                 name: orders-srv
#                 port:
#                   number: 4000
#             path: /api/orders/?(.*)
#             pathType: Exact

#           - backend:
#               service:
#                 name: blogs-srv
#                 port:
#                   number: 4000
#             path: /api/blogs/?(.*)
#             pathType: Exact

#           - backend:
#               service:
#                 name: ui-srv
#                 port:
#                   number: 3000
#             path: /?(.*)
#             pathType: Exact
