# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: products-mongo-depl
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: products-mongo
#   template:
#     metadata:
#       labels:
#         app: products-mongo
#     spec:
#       nodeSelector:
#         name: node1
#       containers:
#         - name: products-mongo
#           image: mongo
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: products-mongo-srv
# spec:
#   type: NodePort
#   selector:
#     app: products-mongo
#   ports:
#     - name: db
#       protocol: TCP
#       port: 27017
#       targetPort: 27017
