apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizes-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizes
  template:
    metadata:
      labels:
        app: quizes
    spec:
      containers:
        - name: quizes
          image: akshaypatil0/quizes
          imagePullPolicy: Never
          env:
            - name: NATS_CLUSTER_ID
              value: fibimarket

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_URL
              value: "http://nats-srv:4222"

            - name: MONGO_URI
              value: "mongodb://quizes-mongo-srv:27017/quizes"

            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

            - name: AWS_ID
              valueFrom:
                secretKeyRef:
                  name: aws-id
                  key: AWS_ID

            - name: AWS_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: quizes-srv
spec:
  selector:
    app: quizes
  ports:
    - name: quizes
      protocol: TCP
      port: 4000
      targetPort: 4000
