apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-depl
  namespace: fibi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      # nodeSelector:
      #   name: node1
      containers:
        - name: ui
          image: akshaypatil0/ui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui-srv
  namespace: fibi
spec:
  type: NodePort
  selector:
    app: ui
  ports:
    - name: ui
      protocol: TCP
      port: 80
      targetPort: 80
