GET http://localhost:4005/api/quizes?userId=6083043e9eadce6bfd80abb2

###
POST http://localhost:4005/api/quizes
Content-Type: application/json

{
    "title":"Cristmas Special",
    "publishedBy":"6083043e9eadce6bfd80abb2",
    "status":1,
    "questions":[
        {
            "question":"Whats is capital of India?",
            "option1":"Mumbai",
            "option2":"Benglore",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"A"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        },
        {
            "question":"Whats is capital of China?",
            "option1":"Shanghai",
            "option2":"Test",
            "option3":"Delhi",
            "option4":"Kolkata",
            "answer":"C"
        }
    ]
}

###
PUT http://localhost:4005/api/quizes/6083fbc7470c75eb6fecb475
Content-Type: application/json

{
    "status":0
}

###
POST http://localhost:4001/api/users/collectReward/
Content-Type: application/json

{
    "userId":"6083043e9eadce6bfd80abb2",
    "quizId":"6083043e9eadce6bfd80abb2",
    "points":10
}
