name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build users docker image
      run: cd ./users && docker build -t akshaypatil0/users .
    - name: Publish users docker image
      run: docker push akshaypatil0/users
    
    - name: Build products docker image
      run: cd products && docker build -t akshaypatil0/products .
    - name: Publish products docker image
      run: docker push akshaypatil0/products

    - name: Build orders docker image
      run: cd orders && docker build -t akshaypatil0/orders .
    - name: Publish orders docker image
      run: docker push akshaypatil0/orders

    - name: Build blogs docker image
      run: cd blogs && docker build -t akshaypatil0/blogs .
    - name: Publish blogs docker image
      run: docker push akshaypatil0/blogs

    - name: Build ui docker image
      run: cd ui && docker build -t akshaypatil0/ui .
    - name: Publish ui docker image
      run: docker push akshaypatil0/ui
